sudo: required
services:
  - docker

# before_install:
#   - docker build -t nathanwkwong/vue-test -f ./client/Dockerfile.dev ./client

# script:
#   - docker run nathanwkwong/vue-test npm test -- --coverage

script:
  - docker build -t nathanwkwong/map-and-track-client ./client
  - docker build -t nathanwkwong/map-and-track-nginx ./nginx
  - docker build -t nathanwkwong/map-and-track-server ./server
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push nathanwkwong/map-and-track-client
  - docker push nathanwkwong/map-and-track-nginx
  - docker push nathanwkwong/map-and-track-server

deploy:
  edge: true
  provider: elasticbeanstalk
  region: ap-northeast-2
  app: Map-And-Track
  env: MapAndTrack-env
  bucket_name: elasticbeanstalk-ap-northeast-2-403354037318
  bucket_path: docker-map-and-track
  on: 
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
