version: 2.1
executors: #declare things that will reuse in all jobs with referencing
    docker-publisher:
      working_directory: ~/map-and-track # directory where steps will run
      environment:
        IMAGE_NAME: nathanwkwong/client #declares a local env variable
      docker:
        - image: circleci/buildpack-deps:stretch #to support executing docker commands
jobs:
  #build: 
  #  executor: docker-publisher
  build-docker:
    working_directory:  ~/map-and-track
    executor: docker-publisher #reference the executor and env variable()IMAGE_NAME
    steps:
      - checkout
      - attach_workspace:
          at: .
      - setup_remote_docker
      - run:
          name: Build latest Docker image
          command: docker build . -t $IMAGE_NAME:latest
      - run:
          name: Archive Docker image
          command: docker save -o image.tar $IMAGE_NAME
      - persist_to_workspace:
          root: ~/map-and-track
          paths:
            - ./image.tar
  publish-docker:
    executor: docker-publisher
    steps:
      - setup_remote_docker
      - run:
          name: Load archived Docker image
          command: docker load -i image.tar
      - run:
          name: Publish Docker Image to Docker Hub
          command: |
            echo "${DOCKERHUB_PASS}" | docker login -u "${DOCKERHUB_USERNAME}" --password-stdin
            docker push $IMAGE_NAME:latest
workflows:
  build_and_deploy:
    jobs:
      - build-docker:
          filters:
            branches:
              only: master
      - publish-docker:
          requires:
            - build-docker
          filters:
            branches:
              only: master