
//mutation
export const LOGIN = 'LOGIN';
export const RESTORE_LOGIN = 'RESTORE_LOGIN';
export const RESTORE_LOGIN_STATE = 'RESTORE_LOGIN_STATE';
export const LOGOUT = 'LOGOUT';
export const GET_JOINED_ROOMS = 'GET_JOINED_ROOMS';
export const GET_CREATED_ROOMS = 'GET_CREATED_ROOMS';

export const SET_IS_TRACE_SELF_MODE_ON = 'SET_IS_TRACE_SELF_MODE_ON';
export const SET_IS_TRACE_OTHERS_MODE_ON = 'SET_IS_TRACE_OTHERS_MODE_ON';
export const SET_IS_MANUAL_MODE_ON = 'SET_IS_MANUAL_MODE_ON';