export const JOIN_ROOM = 'JOIN_ROOM';
export const INIT_ROOM = 'INIT_ROOM';

export const UPDATE_ALL_MAP_TRACES = 'UPDATE_ALL_MAP_TRACES';
export const UPDATE_SELF_MAP_TRACE = 'UPDATE_SELF_MAP_TRACE';
export const UPDATE_LAST_UPDATED_MAP_TRACE_ID = 'UPDATE_LAST_UPDATED_MAP_TRACE_ID';

export const ADD_USER = 'ADD_USER';
export const ADD_MAP_TRACE = 'ADD_MAP_TRACE';
export const ADD_MAP_SPOT = 'ADD_MAP_SPOT';

export const SET_MAP = 'SET_MAP';
export const SET_SOCKET = 'SET_SOCKET';
export const SET_SOCKET_QUERY = 'SET_SOCKET_QUERY'
export const SET_IS_SHOW_MAP_LOG = 'SET_IS_SHOW_MAP_LOG';
export const SET_COORDINATES = 'SET_COORDINATES';
export const SET_SELF_MAP_TRACE_ID = 'SET_SELF_MAP_TRACE_ID';
export const SET_USERS_IS_TRACE_SELF_MODE_ON = 'SET_USERS_IS_TRACE_SELF_MODE_ON';

export const REMOVE_USER = 'REMOVE_USER';
export const REMOVE_ALL_MAP_TRACES = 'REMOVE_ALL_MAP_TRACES';

export const EXIT_ROOM = 'EXIT_ROOM';


